apiVersion: v1
kind: Service
metadata:
  name: reranking-ms
spec:
  selector:
    app: reranking-ms
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
