apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-model
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/models" # Change to an appropriate path if using static provisioning
